# Created using wingetcreate 1.2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: maluoi.openxr-explorer
PackageVersion: 1.4
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: wix
  InstallerUrl: https://github.com/maluoi/openxr-explorer/releases/download/v1.4/openxr-explorer-win-x64.msi
  InstallerSha256: C92B7077F456EA891AB17D2B1CCDC67A28A1057868B2E597E28145A2BF432299
  InstallModes:
  - silentWithProgress
  - silent
  - interactive
  UpgradeBehavior: install
  ProductCode: '{FA33FFD0-CC6D-4569-BA6A-3858D4D57A39}'
ManifestType: installer
ManifestVersion: 1.4.0
