# Created using wingetcreate 1.2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: maluoi.openxr-explorer
PackageVersion: 1.4
PackageLocale: en-US
Publisher: maluoi
PublisherUrl: https://github.com/maluoi
PublisherSupportUrl: https://github.com/maluoi/openxr-explorer
Author: Nick Klingensmith
PackageName: openxr-explorer
PackageUrl: https://github.com/maluoi/openxr-explorer
License: MIT
LicenseUrl: https://github.com/maluoi/openxr-explorer/blob/main/LICENSE
ShortDescription: A cross-platform OpenXR capabilities explorer and runtime switcher with a CLI and GUI.
Moniker: openxr-explorer
ManifestType: defaultLocale
ManifestVersion: 1.4.0
